[package]
name = "rtsp-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.2.2"
base64 = "0.13.0"
ctrlc = "3.3.0"
openh264 = "0.5.0"
chrono = "0.4"
image = "0.24"
colored = "2.0"